# Generated by Django 4.2.3 on 2023-09-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
